### ISSUE TITLE
ShowCoins component localisation issue.

### ISSUE THREAD

**Issue by luochuanyuewu** [FlipWebApps/GameFramework#6] opened 2016-08-02 15:25 UTC
I added a ShowCoins component(GameFramework | GameStructure | Player) to a ui element with text component, then set the localisation key. the problem is when i change the game language globally, the text won't change immediately unless reload scene. 
   I also tried adding localisetext component on the same ui element which led to another odd result.

**Comment by FlipWebApps** [comment] 2016-08-02 16:04
Submitted an update so that all ShowValueAnimatedMessaging derived classes (including ShowCoins) will react to localisation changes immediately. If you can check and confirm.

Can you provide more information on the other issue caused by the localisetext component?

**Comment by luochuanyuewu** [comment] 2016-08-02 16:16
I am not sure whether the localisetext component having issue, when i put ShowCoins and localisetext  component on the same GO, the first one's localisation functionality are overwrited  by second one. the result is "Gold:{0}" .

**Comment by FlipWebApps** [comment] 2016-08-02 18:56
I think that will always be the case as I believe they get executed in the order that they appear and unless set a different Textarget in ShowCoins they will both work and try and update the same item.

Let me know if there is any particular reason that you need both, otherwise if the other issue is resolved they you can just close this issue.

**Closed** 2016-08-03 04:54 UTC
